version: "3"

services:

  sg-backend:
    build:
      context: './sensorgnome-server'
    image: ubuntu:latest
    container_name: sgs-backend
    hostname: sgs-backend
    restart: on-failure
    ports:
      - "59022:59022"
      - "59023:59023"
      - "59024:59024"
      - "59025:59025"
      - "59026:59026"
      - "59027:59027"
    volumes:
      - ./docker-volumes/sensorgnome-server/logs:/sensorgnome-logs
      - ./docker-volumes/sensorgnome-server/database/sg_remote.sqlite:/home/sg_remote/sg_remote.sqlite
      - ./docker-volumes/sensorgnome-server/ssh-keys/.ssh:/home/sg_remote/.ssh
      - ./docker-volumes/sensorgnome-server/status/index.md:/home/johnb/src/sensorgnome-website/content/status/index.md
    command:
      sh -c "/sensorgnome-server-software/sensorgnomeServer >> /sensorgnome-logs/sensorgnomeServer.log.txt 2>&1"
    stdin_open: true
    tty: true
    networks:
      - sg_network

  nginx:
    image: nginx:alpine
    container_name: sgs-nginx
    hostname: sgs-nginx
    ports:
      - "10080:80"
      - "10443:443"
    expose:
      - "1313"
    volumes:
      - ./docker-volumes/nginx/etc/nginx:/etc/nginx
      - ./docker-volumes/nginx/etc/ssl:/etc/ssl
      - ./docker-volumes/nginx/logs:/var/log/nginx
    networks:
      - sg_network

  sg-hugo:
    build:
      context: './hugo-static'
    image: ubuntu:latest
    container_name: sgs-hugo
    hostname: sgs-hugo
    restart: on-failure
    expose:
      - "1313"
      - "443"
    volumes:
      - ./docker-volumes/hugo/logs:/hugo-logs
      - ./docker-volumes/sensorgnome-server/status/index.md:/hugo/content/status/index.md
    command:
      sh -c "cd /hugo/sensorgnome-website && hugo server --logFile /hugo-logs/hugolog.txt --liveReloadPort=443 --port=1313 --bind=0.0.0.0 --baseUrl=sensorgnome.org --appendPort=false"
    stdin_open: true
    tty: true
    networks:
      - sg_network

networks:
  sg_network:
    driver: bridge
